version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - demo-net
    logging:
        driver: "json-file"
        options:kafka-eagle
          max-size: "10m"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      #HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      HOSTNAME_COMMAND: "eval cat /etc/hostname"
      #KAFKA_ADVERTISED_HOST_NAME: demo1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
    deploy:
      mode: global
    networks:
      - demo-net

  kafka-eagle:
    build:
      context: ./kafka-eagle
      dockerfile: Dockerfile
    image: 35.201.148.193:5000/kafka-eagle
    ports:
      - "8048:8048"
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
    networks:
      - keypo-dump-net
    deploy:
      mode: global
      placement:
        constraints: [node.labels.rabbitmq1 == true]

networks:
  demo-net:
    external: true
